import React,{useEffect,useRef}from'react';import{X,Search}from'lucide-react';
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'success'|'warning'|'danger'|'info'|'neutral'}){return <span className={`badge ${tone}`}>{children}</span>}
export function Avatar({name,size='md'}:{name:string;size?:'sm'|'md'|'lg'}){const initials=name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();return <span className={`avatar ${size}`} aria-label={name}>{initials}</span>}
export function StatCard({label,value,change,icon:Icon,onClick}:{label:string;value:string|number;change?:string;icon:React.ElementType;onClick?:()=>void}){const content=<><div className="stat-top"><span>{label}</span><span className="icon-box"><Icon size={18}/></span></div><strong>{value}</strong>{change&&<small className={change.startsWith('-')?'negative':'positive'}>{change}</small>}</>;return onClick?<button className="stat-card stat-card-button" onClick={onClick}>{content}</button>:<div className="stat-card">{content}</div>}
export function PageHeader({title,subtitle,action}:{title:string;subtitle?:string;action?:React.ReactNode}){return <div className="page-header"><div><span className="eyebrow">IHPAU HR SUITE</span><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action&&<div className="actions">{action}</div>}</div>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon">✦</div><h3>{title}</h3><p>{description}</p>{action}</div>}
export function SearchInput({value,onChange,placeholder='Search...',onFocus}:{value:string;onChange:(v:string)=>void;placeholder?:string;onFocus?:()=>void}){return <label className="search-input"><Search size={16}/><input value={value} onChange={e=>onChange(e.target.value)} onFocus={onFocus} placeholder={placeholder} aria-label={placeholder}/></label>}
export function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&ref.current){const els:HTMLElement[]=Array.from(ref.current.querySelectorAll<HTMLElement>('button,input,select,textarea,a,[tabindex]:not([tabindex="-1"])')) as HTMLElement[];if(!els.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',onKey);requestAnimationFrame(()=>ref.current?.querySelector<HTMLElement>('button,input,select,textarea,a')?.focus());return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',onKey)}},[onClose]);return <div className="modal-backdrop" onMouseDown={onClose}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby="modal-title" className={`modal ${wide?'modal-wide':''}`} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h3 id="modal-title">{title}</h3><button className="icon-btn" onClick={onClose} aria-label="Close"><X size={18}/></button></div>{children}</div></div>}
export function Toast({message,tone='success',onClose}:{message:string;tone?:'success'|'error'|'info';onClose:()=>void}){useEffect(()=>{const t=window.setTimeout(onClose,3500);return()=>window.clearTimeout(t)},[onClose]);return <div className={`toast ${tone}`} role="status"><span>{message}</span><button onClick={onClose} aria-label="Dismiss notification"><X size={15}/></button></div>}
export function Field({label,children,required}:{label:string;children:React.ReactNode;required?:boolean}){return <label className="field"><span>{label}{required&&<b aria-hidden="true"> *</b>}</span>{children}</label>}
